--[[
	@class ClientMain
]]
local loader = game:GetService("ReplicatedStorage"):WaitForChild("Aimbot"):WaitForChild("loader")
local require = require(loader).bootstrapGame(loader.Parent)

local serviceBag = require("ServiceBag").new()
serviceBag:GetService(require("CmdrServiceClient"))
serviceBag:GetService(require("RagdollServiceClient"))
serviceBag:GetService(require("HighlightServiceClient"))
serviceBag:GetService(require("AimbotTranslator"))
serviceBag:GetService(require("GunServiceClient"))
serviceBag:GetService(require("HealthServiceClient"))
serviceBag:GetService(require("ObjectHitServiceClient"))
serviceBag:GetService(require("GunModelControllerClient"))
serviceBag:GetService(require("PlayerHitServiceClient"))
serviceBag:GetService(require("InputTypeServiceClient"))
serviceBag:GetService(require("RecoilServiceClient"))
serviceBag:GetService(require("BulletTracerServiceClient"))
serviceBag:GetService(require("SoundsServiceClient"))
serviceBag:GetService(require("EliminatedUIService"))
serviceBag:GetService(require("DamageAmountUIService"))
serviceBag:GetService(require("DamageDirectionUIService"))
serviceBag:GetService(require("HitmarkerUIService"))
serviceBag:GetService(require("PlayerTrackerUIService"))
serviceBag:GetService(require("MobileButtonsUIService"))
serviceBag:GetService(require("AmmoUI"))
serviceBag:GetService(require("ReloadUI"))
serviceBag:GetService(require("HealthUI"))
serviceBag:GetService(require("CrosshairUI"))
serviceBag:Init()
serviceBag:Start()
